# Generated by Django 5.1.2 on 2024-10-17 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0006_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.cake')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.cart')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='cakes',
            field=models.ManyToManyField(through='sweetspot_app.CartCake', to='sweetspot_app.cake'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.order')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='sweetspot_app.OrderItem', to='sweetspot_app.cake'),
        ),
    ]
