# Generated by Django 5.1.2 on 2024-10-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0007_cartcake_alter_cart_cakes_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cakes',
        ),
    ]
